/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package megastore-0.1.0.0 */
#ifndef VERSION_megastore
#define VERSION_megastore "0.1.0.0"
#endif /* VERSION_megastore */
#ifndef MIN_VERSION_megastore
#define MIN_VERSION_megastore(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_megastore */
/* package JuicyPixels-3.3.7 */
#ifndef VERSION_JuicyPixels
#define VERSION_JuicyPixels "3.3.7"
#endif /* VERSION_JuicyPixels */
#ifndef MIN_VERSION_JuicyPixels
#define MIN_VERSION_JuicyPixels(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 7)
#endif /* MIN_VERSION_JuicyPixels */
/* package adjunctions-4.4.2 */
#ifndef VERSION_adjunctions
#define VERSION_adjunctions "4.4.2"
#endif /* VERSION_adjunctions */
#ifndef MIN_VERSION_adjunctions
#define MIN_VERSION_adjunctions(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_adjunctions */
/* package base-4.17.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.17.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 0)
#endif /* MIN_VERSION_base */
/* package binary-0.8.9.1 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.1"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.3.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.3.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 3)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.6 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.6"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 6)
#endif /* MIN_VERSION_containers */
/* package directory-1.3.7.1 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.7.1"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 7)
#endif /* MIN_VERSION_directory */
/* package ghc-9.4.3 */
#ifndef VERSION_ghc
#define VERSION_ghc "9.4.3"
#endif /* VERSION_ghc */
#ifndef MIN_VERSION_ghc
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_VERSION_ghc */
/* package hashable-1.4.1.0 */
#ifndef VERSION_hashable
#define VERSION_hashable "1.4.1.0"
#endif /* VERSION_hashable */
#ifndef MIN_VERSION_hashable
#define MIN_VERSION_hashable(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_hashable */
/* package lens-5.2 */
#ifndef VERSION_lens
#define VERSION_lens "5.2"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  2 || \
  (major1) == 5 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_lens */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package random-1.2.1.1 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package text-2.0.1 */
#ifndef VERSION_text
#define VERSION_text "2.0.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_text */
/* package text-show-3.10 */
#ifndef VERSION_text_show
#define VERSION_text_show "3.10"
#endif /* VERSION_text_show */
#ifndef MIN_VERSION_text_show
#define MIN_VERSION_text_show(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  10 || \
  (major1) == 3 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_text_show */
/* package vector-0.12.3.1 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.3.1"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_vector */
/* package zlib-0.6.3.0 */
#ifndef VERSION_zlib
#define VERSION_zlib "0.6.3.0"
#endif /* VERSION_zlib */
#ifndef MIN_VERSION_zlib
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_zlib */

/* tool gcc-13.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "13.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  0 || \
  (major1) == 13 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.4.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.4.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.4.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.4.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.27.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.27.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  27 || \
  (major1) == 2 && (major2) == 27 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.4.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.4.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "megastore-0.1.0.0-Gr8TNESROXy43VbOYJWT7I"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "megastore-0.1.0.0-Gr8TNESROXy43VbOYJWT7I"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package megastore-0.1.0.0 */
#ifndef VERSION_megastore
#define VERSION_megastore "0.1.0.0"
#endif /* VERSION_megastore */
#ifndef MIN_VERSION_megastore
#define MIN_VERSION_megastore(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_megastore */
/* package JuicyPixels-3.3.7 */
#ifndef VERSION_JuicyPixels
#define VERSION_JuicyPixels "3.3.7"
#endif /* VERSION_JuicyPixels */
#ifndef MIN_VERSION_JuicyPixels
#define MIN_VERSION_JuicyPixels(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 7)
#endif /* MIN_VERSION_JuicyPixels */
/* package adjunctions-4.4.2 */
#ifndef VERSION_adjunctions
#define VERSION_adjunctions "4.4.2"
#endif /* VERSION_adjunctions */
#ifndef MIN_VERSION_adjunctions
#define MIN_VERSION_adjunctions(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_adjunctions */
/* package base-4.17.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.17.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 0)
#endif /* MIN_VERSION_base */
/* package binary-0.8.9.1 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.1"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.3.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.3.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 3)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.6 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.6"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 6)
#endif /* MIN_VERSION_containers */
/* package directory-1.3.7.1 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.7.1"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 7)
#endif /* MIN_VERSION_directory */
/* package ghc-9.4.3 */
#ifndef VERSION_ghc
#define VERSION_ghc "9.4.3"
#endif /* VERSION_ghc */
#ifndef MIN_VERSION_ghc
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_VERSION_ghc */
/* package hashable-1.4.1.0 */
#ifndef VERSION_hashable
#define VERSION_hashable "1.4.1.0"
#endif /* VERSION_hashable */
#ifndef MIN_VERSION_hashable
#define MIN_VERSION_hashable(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_hashable */
/* package lens-5.2 */
#ifndef VERSION_lens
#define VERSION_lens "5.2"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  2 || \
  (major1) == 5 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_lens */
/* package megastore-0.1.0.0 */
#ifndef VERSION_megastore
#define VERSION_megastore "0.1.0.0"
#endif /* VERSION_megastore */
#ifndef MIN_VERSION_megastore
#define MIN_VERSION_megastore(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_megastore */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package random-1.2.1.1 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package text-2.0.1 */
#ifndef VERSION_text
#define VERSION_text "2.0.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_text */
/* package text-show-3.10 */
#ifndef VERSION_text_show
#define VERSION_text_show "3.10"
#endif /* VERSION_text_show */
#ifndef MIN_VERSION_text_show
#define MIN_VERSION_text_show(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  10 || \
  (major1) == 3 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_text_show */
/* package vector-0.12.3.1 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.3.1"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_vector */
/* package zlib-0.6.3.0 */
#ifndef VERSION_zlib
#define VERSION_zlib "0.6.3.0"
#endif /* VERSION_zlib */
#ifndef MIN_VERSION_zlib
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_zlib */

/* tool gcc-13.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "13.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  0 || \
  (major1) == 13 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.4.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.4.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.4.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.4.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.27.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.27.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  27 || \
  (major1) == 2 && (major2) == 27 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.4.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.4.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "megastore-0.1.0.0-FB9u9X1AMoyKYSINU4wYlX-megastore"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
